FROM ubuntu:latest
RUN apt-get update \ 
   && apt-get install -y apache2

WORKDIR /var/www/html

COPY index.html /var/www/html/

WORKDIR /var/www/html

CMD ["apache2"],"-D", "FOREGROUND"]
EXPOSE 80

